version: 2
updates:
- package-ecosystem: npm
  directory: "/api"
  schedule:
    interval: weekly
  open-pull-requests-limit: 0
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: weekly
  open-pull-requests-limit: 0
